# Generated by Django 4.0.3 on 2022-04-15 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingUI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_number', models.IntegerField()),
                ('is_admin', models.BooleanField(default='False')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_withdrawal', models.BooleanField()),
                ('amount', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingUI.bankinfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='user_names',
            name='info',
        ),
        migrations.RemoveField(
            model_name='user_names',
            name='money',
        ),
        migrations.RenameModel(
            old_name='User_Info',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='User_Money',
        ),
        migrations.DeleteModel(
            name='User_Names',
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='customer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingUI.customer'),
        ),
    ]
