# Generated by Django 4.0.3 on 2022-04-16 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingUI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='customer_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, serialize='True', to='BankingUI.customer'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, serialize='True', to='BankingUI.bankinfo'),
        ),
    ]
