# Generated by Django 4.0.3 on 2022-04-15 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankingUI', '0002_bankinfo_transactions_remove_user_names_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankinfo',
            name='is_admin',
        ),
    ]
