# Generated by Django 4.0.3 on 2022-04-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankingUI', '0004_alter_transactions_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
